version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/skelerest-sb-plugin
    steps:
      - checkout
      - run:
          name: pip env
          command: |
            sudo pip install pipenv==2022.4.8
            pipenv install
      - run:
          name: install dependencies
          command: pipenv run pip install -r ./requirements.txt
      - run:
          name: run tests
          command: pipenv run coverage run --source skelerest/ -m pytest && pipenv run coverage xml -o codecov.xml
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash) -f codecov.xml
